* Capture Basics
    Capture has as its primary goal of getting it out of your mind now.
    When you capture you are grabbing a concept and quickly putting it in your inbox 
    for later refiling. Orgs and vscode make this possible through a hybrid approach.
    Orgs does the capture operation while vscode handles the text input.

    The orgs server allows you to define capture targets in its configuration file.
    These are synced with your vscode settings file automatically. Your vscode settings file
    then allows you to extend these capture targets with a snippet template to use when 
    filling out one of these captures. These snippets use the normal vscode snippet rules:

    As an example, variables should work just fine:
    [[https://code.visualstudio.com/docs/editor/userdefinedsnippets][VsCode Snippet Rules]] 

** Capture Targets
    Capture targets come in a variety of types:
    - entry - This is a subnode of whatever the target it pointing at.
    - plain - This is plain text added somewhere in the node.

    NOT YET SUPPORTED PAST THIS POINT
    - item  - this is a list item added to the end of a list in the target.
    - checkitem - this is a checkbox list item added to the end of a checklist in the target (or end of target)
    - table-line - This is a line of a table added to whatever table is in the document
